[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crew_gambling_project"
version = "0.1.0"
dependencies = [
    "scrapegraph-py"
]

[tool.setuptools.packages.find]
where = ["crew_gambling_project"]
